#!/bin/sh
# Shell-level tests for scripts/barry-checkpoint.sh.
#
# Exercises barry-checkpoint.sh entirely inside disposable, temporary fake
# ArchiveFS repositories (their own `git init`, their own Cargo.toml /
# Cargo.lock, their own copy of the script under scripts/) - it never
# touches this real repository's working tree, git history, or
# .barry-cache/. Run it directly:
#   sh tests/test_barry_checkpoint.sh
# Exits 0 if every test passes, 1 if any test fails.
set -eu

script_dir=$(dirname -- "$0")
script_dir=$(CDPATH= cd -- "$script_dir" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
barry_checkpoint_sh="$repo_root/scripts/barry-checkpoint.sh"

[ -f "$barry_checkpoint_sh" ] || {
    printf 'test_barry_checkpoint.sh: cannot find %s\n' "$barry_checkpoint_sh" >&2
    exit 1
}

# A fixed, portable author identity for every commit this test suite
# makes, so it never depends on (or pollutes) the host's ~/.gitconfig.
GIT_AUTHOR_NAME="Barry Test"; export GIT_AUTHOR_NAME
GIT_AUTHOR_EMAIL="barry-test@example.invalid"; export GIT_AUTHOR_EMAIL
GIT_COMMITTER_NAME="Barry Test"; export GIT_COMMITTER_NAME
GIT_COMMITTER_EMAIL="barry-test@example.invalid"; export GIT_COMMITTER_EMAIL

pass_count=0
fail_count=0

ok() {
    pass_count=$((pass_count + 1))
    printf 'ok - %s\n' "$*"
}

bad() {
    fail_count=$((fail_count + 1))
    printf 'NOT OK - %s\n' "$*"
}

# assert_success DESCRIPTION CMD... : runs CMD, records ok/bad. Safe under
# `set -e` because the failing command only ever appears in an `if`
# condition, which POSIX exempts from triggering -e.
assert_success() {
    description="$1"
    shift
    if "$@" >/dev/null 2>&1; then
        ok "$description"
    else
        bad "$description (expected success, command failed)"
    fi
}

assert_failure() {
    description="$1"
    shift
    if "$@" >/dev/null 2>&1; then
        bad "$description (expected failure, command succeeded)"
    else
        ok "$description"
    fi
}

assert_file_exists() {
    if [ -f "$2" ]; then ok "$1"; else bad "$1 (missing: $2)"; fi
}

assert_contains() {
    case "$2" in
        *"$3"*) ok "$1" ;;
        *) bad "$1 (did not find: $3)" ;;
    esac
}

assert_not_contains() {
    case "$2" in
        *"$3"*) bad "$1 (unexpectedly found: $3)" ;;
        *) ok "$1" ;;
    esac
}

assert_equal() {
    if [ "$2" = "$3" ]; then ok "$1"; else bad "$1 (expected [$3], got [$2])"; fi
}

# make_fake_repo DIR - builds a minimal but genuine ArchiveFS-shaped
# repository under DIR: a workspace Cargo.toml naming archivefs-core, an
# empty crates/archivefs-core directory, a matching Cargo.lock, its own
# git history (one commit), and its own copy of barry-checkpoint.sh under
# scripts/ (so the script's own-location-based repo-root resolution finds
# *this* fake repo, never the real one).
make_fake_repo() {
    dir="$1"
    version="${2:-9.9.9-test}"
    mkdir -p -- "$dir/crates/archivefs-core" "$dir/scripts"
    cat >"$dir/Cargo.toml" <<EOF
[workspace]
members = [
    "crates/archivefs-core",
]
resolver = "2"

[workspace.package]
version = "$version"
edition = "2024"
EOF
    cat >"$dir/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "archivefs-core"
version = "$version"
dependencies = [
]
EOF
    cp -- "$barry_checkpoint_sh" "$dir/scripts/barry-checkpoint.sh"
    chmod +x -- "$dir/scripts/barry-checkpoint.sh"
    ( cd "$dir" && git init --quiet --initial-branch=main )
    # Mirror the real repository's .git/info/exclude entry for
    # .barry-cache/, so this fake repo's `git status`/`git diff` behavior
    # around the Barry file matches production exactly.
    printf '.barry-cache/\n' >>"$dir/.git/info/exclude"
    ( cd "$dir" && git add -A
      cd "$dir" && git commit --quiet -m "Initial fake commit" )
}

echo "=== test: runs successfully from an unrelated directory and creates the Barry file ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
outside=$(mktemp -d)
out=$(cd "$outside" && "$work/repo/scripts/barry-checkpoint.sh")
assert_contains "prints the updated file path" "$out" "$work/repo/.barry-cache/project-state.md"
assert_file_exists "Barry file was created" "$work/repo/.barry-cache/project-state.md"
content=$(cat "$work/repo/.barry-cache/project-state.md")
assert_contains "contains START marker" "$content" "<!-- BARRY FACTS START -->"
assert_contains "contains END marker" "$content" "<!-- BARRY FACTS END -->"
assert_contains "contains the workspace version" "$content" "9.9.9-test"
assert_contains "contains the branch name" "$content" "Branch: main"
assert_contains "contains a full commit SHA line" "$content" "Commit: "
assert_contains "reports no local tag" "$content" "Latest local tag at HEAD: none"
assert_contains "reports a clean tree" "$content" "(clean)"
assert_contains "reports Cargo.lock matches" "$content" "matches workspace version (9.9.9-test)"
head_sha=$(cd "$work/repo" && git rev-parse HEAD)
assert_contains "commit SHA matches the fake repo's real HEAD" "$content" "$head_sha"
rm -rf -- "$work" "$outside"

echo "=== test: never modifies any tracked source file ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
before_status=$(cd "$work/repo" && git status --short)
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
after_status=$(cd "$work/repo" && git status --short)
# .barry-cache/ is untracked (matches the real repo's .git/info/exclude
# convention is not replicated here, but the file is never `git add`ed by
# the script either way), so the only permitted status-line delta is the
# new untracked .barry-cache/ directory itself - no tracked file changes.
assert_not_contains "no tracked file shows as modified (M)" "$after_status" " M "
rm -rf -- "$work"

echo "=== test: never creates a commit, tag, or changes the branch ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
commits_before=$(cd "$work/repo" && git rev-list --count HEAD)
tags_before=$(cd "$work/repo" && git tag | wc -l)
branch_before=$(cd "$work/repo" && git rev-parse --abbrev-ref HEAD)
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
commits_after=$(cd "$work/repo" && git rev-list --count HEAD)
tags_after=$(cd "$work/repo" && git tag | wc -l)
branch_after=$(cd "$work/repo" && git rev-parse --abbrev-ref HEAD)
assert_equal "commit count is unchanged" "$commits_after" "$commits_before"
assert_equal "tag count is unchanged" "$tags_after" "$tags_before"
assert_equal "branch is unchanged" "$branch_after" "$branch_before"
rm -rf -- "$work"

echo "=== test: picks up a local tag pointing at HEAD ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
( cd "$work/repo" && git tag v9.9.9-test )
out=$("$work/repo/scripts/barry-checkpoint.sh" 2>&1)
content=$(cat "$work/repo/.barry-cache/project-state.md")
assert_contains "reports the tag pointing at HEAD" "$content" "Latest local tag at HEAD: v9.9.9-test"
: "$out"
rm -rf -- "$work"

echo "=== test: reports unstaged and staged changes separately ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
echo "more content" >>"$work/repo/Cargo.toml"
echo "brand new file" >"$work/repo/NEWFILE.txt"
( cd "$work/repo" && git add NEWFILE.txt )
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
content=$(cat "$work/repo/.barry-cache/project-state.md")
assert_contains "status shows the modified Cargo.toml" "$content" "Cargo.toml"
assert_contains "status shows the new untracked file" "$content" "NEWFILE.txt"
assert_contains "unstaged diff --stat is non-empty" "$content" "Cargo.toml | "
assert_contains "staged diff --stat mentions the new file" "$content" "NEWFILE.txt"
rm -rf -- "$work"

echo "=== test: detects a Cargo.lock version mismatch ==="
work=$(mktemp -d)
make_fake_repo "$work/repo" "9.9.9-test"
cat >"$work/repo/Cargo.lock" <<'EOF'
version = 4

[[package]]
name = "archivefs-core"
version = "8.8.8-stale"
dependencies = [
]
EOF
( cd "$work/repo" && git add -A && git commit --quiet -m "stale lock" )
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
content=$(cat "$work/repo/.barry-cache/project-state.md")
assert_contains "reports the Cargo.lock mismatch" "$content" "MISMATCH - Cargo.lock has archivefs-core 8.8.8-stale, workspace is 9.9.9-test"
rm -rf -- "$work"

echo "=== test: reports a missing Cargo.lock clearly ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
rm -- "$work/repo/Cargo.lock"
( cd "$work/repo" && git add -A && git commit --quiet -m "remove lock" )
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
content=$(cat "$work/repo/.barry-cache/project-state.md")
assert_contains "reports Cargo.lock not found" "$content" "Cargo.lock check: Cargo.lock not found"
rm -rf -- "$work"

echo "=== test: preserves hand-written content outside the markers, updates only facts ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
barry_file="$work/repo/.barry-cache/project-state.md"
printf '\n## Hand-written notes\n\nDo not touch this paragraph.\n' >>"$barry_file"
first_run_content=$(cat "$barry_file")
first_sha=$(cd "$work/repo" && git rev-parse HEAD)

# A second, genuinely different commit so the facts section must change.
echo "another line" >>"$work/repo/Cargo.toml"
( cd "$work/repo" && git add -A && git commit --quiet -m "second commit" )
second_sha=$(cd "$work/repo" && git rev-parse HEAD)

"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
second_run_content=$(cat "$barry_file")

assert_contains "hand-written paragraph survives a second run" "$second_run_content" "Do not touch this paragraph."
assert_contains "facts now show the new commit SHA" "$second_run_content" "$second_sha"
assert_not_contains "facts no longer show the old commit SHA as HEAD" "$second_run_content" "Commit: $first_sha"
: "$first_run_content"
rm -rf -- "$work"

echo "=== test: appends a facts block when no markers exist yet ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
mkdir -p -- "$work/repo/.barry-cache"
printf '# Hand-written Barry file\n\nSome existing notes with no markers at all.\n' \
    >"$work/repo/.barry-cache/project-state.md"
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
content=$(cat "$work/repo/.barry-cache/project-state.md")
assert_contains "original heading survives" "$content" "Some existing notes with no markers at all."
assert_contains "facts block was appended" "$content" "<!-- BARRY FACTS START -->"
rm -rf -- "$work"

echo "=== test: idempotent - running twice with no repo changes yields the same facts ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
first=$(cat "$work/repo/.barry-cache/project-state.md")
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
second=$(cat "$work/repo/.barry-cache/project-state.md")
# Strip the "Generated:" timestamp line before comparing, since that is
# the one field expected to differ between two real-time runs.
first_stable=$(printf '%s\n' "$first" | grep -v '^- Generated:')
second_stable=$(printf '%s\n' "$second" | grep -v '^- Generated:')
assert_equal "everything except the timestamp is identical" "$second_stable" "$first_stable"
rm -rf -- "$work"

echo "=== test: leaves no leftover temp files behind ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
"$work/repo/scripts/barry-checkpoint.sh" >/dev/null
leftovers=$(find "$work/repo/.barry-cache" -name '.project-state.md.tmp.*')
assert_equal "no .project-state.md.tmp.* files remain" "$leftovers" ""
rm -rf -- "$work"

echo "=== test: fails clearly outside any git repository ==="
work=$(mktemp -d)
make_fake_repo "$work/repo"
plain_dir=$(mktemp -d)
cp -- "$work/repo/scripts/barry-checkpoint.sh" "$plain_dir/barry-checkpoint.sh"
errfile=$(mktemp)
if "$plain_dir/barry-checkpoint.sh" >/dev/null 2>"$errfile"; then
    bad "exits non-zero outside a git repository"
else
    ok "exits non-zero outside a git repository"
fi
assert_contains "error message mentions git repository" "$(cat "$errfile")" "git repository"
rm -f -- "$errfile"
rm -rf -- "$work" "$plain_dir"

echo "=== test: fails clearly inside a git repo that is not ArchiveFS ==="
work=$(mktemp -d)
other_repo="$work/other-repo"
mkdir -p -- "$other_repo/scripts"
cp -- "$barry_checkpoint_sh" "$other_repo/scripts/barry-checkpoint.sh"
chmod +x -- "$other_repo/scripts/barry-checkpoint.sh"
printf '[package]\nname = "unrelated"\n' >"$other_repo/Cargo.toml"
( cd "$other_repo" && git init --quiet --initial-branch=main
  cd "$other_repo" && git add -A
  cd "$other_repo" && git commit --quiet -m "unrelated repo" )
errfile=$(mktemp)
if "$other_repo/scripts/barry-checkpoint.sh" >/dev/null 2>"$errfile"; then
    bad "exits non-zero inside a non-ArchiveFS git repository"
else
    ok "exits non-zero inside a non-ArchiveFS git repository"
fi
assert_contains "error message names the reason" "$(cat "$errfile")" "ArchiveFS repository"
rm -f -- "$errfile"
rm -rf -- "$work"

echo
printf 'Results: %s passed, %s failed\n' "$pass_count" "$fail_count"
[ "$fail_count" -eq 0 ]
